config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'sessions#new'
  get 'chatroom', to: 'chatroom#index'
  get 'login',  to: 'sessions#new'
  post 'login',  to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  post 'message', to: 'messages#create'
  get 'signup', to: 'users#new'
  get 'my_friends', to: 'users#my_friends'
  get 'search_friends', to: 'users#search'
  post 'add_friend', to: 'users#add_friend'

  resources :users, only: [:show]
  resources :friendships
  resources :users, except: [:new]


  mount ActionCable.server, at: '/cable'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :user
  belongs_to :friend, :class_name => 'User'
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  validates :body, presence: true
  scope :custom_display, ->  { order(:created_at).last(20) }
end

app/models/user.rb
class User < ApplicationRecord
  validates :username, presence: true, length: { minimum: 3, maximum: 20 },
            uniqueness: { case_sensitive: false }
  has_many :messages
  has_secure_password
  has_one_attached :avatar
  has_many :friendships
  has_many :friends, through: :friendships

  def self.search(param)
    param.strip!
    param.downcase!
    to_send_back = (username_matches(param)).uniq
    return nil unless to_send_back
    to_send_back
  end

  def self.username_matches(param)
    matches('username', param)
  end

  def self.matches(field_name, param)
    User.where("#{field_name} like ?", "%#{param}%")
  end

  def except_current_user(users)
    users.reject { |user| user.id == self.id }
  end

  def not_friends_with?(friend_id)
    friendships.where(friend_id: friend_id).count < 1
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base


    helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in?
      flash[:danger] = "You must be logged in to perform that action."
      redirect_to login_path
    end
  end

  end

app/controllers/chatroom_controller.rb
class ChatroomController < ApplicationController
  before_action :require_user

  def index
    @message = Message.new
    @messages = Message.custom_display
  end

end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController

  def destroy
    @friendship = current_user.friendships.where(friend_id: params[:id]).first
    @friendship.destroy
    flash[:notice] = "Friends was successfully removed."
    redirect_to my_friends_path
  end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :require_user

  def create
    message = current_user.messages.build(message_params)
    if message.save
      ActionCable.server.broadcast "chatroom_channel",
                                      mod_message: message_render(message)
    end
  end

  private

  def message_params
    params.require(:message).permit(:body)
  end

  def message_render(message)
    render(partial: 'message', locals: {message: message})
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :logged_in_redirect, only: [:new, :create]

  def new

  end

  def create
    user = User.find_by(username: params[:session][:username])
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:success] = "You've successfully logged in"
      redirect_to chatroom_path
    else
      flash.now[:error] = "There was something wrong with your login information"
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = "You've successfully logged out"
    redirect_to login_path
  end

  private

  def logged_in_redirect
    if logged_in?
      flash[:error] = "You're already logged in"
      redirect_to chatroom_path
    end

  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :signed_up, only: [:new, :create]
  before_action :require_user, except: [:new, :create]
  def new
    @user = User.new

  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:success] = "Welcome to the MessageMe app #{@user.username}"
      redirect_to chatroom_path(@user)
    else
      render 'new'
    end
  end

  def index
    @users = User.paginate(page: params[:page], per_page: 5)
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
  end

  def my_friends
    @friendships = current_user.friends
  end

  def search
    if params[:search_param].blank?
       flash.now[:danger] = "You have entered an empty search string"
     else
       @users = User.search(params[:search_param])
       @users = current_user.except_current_user(@users)
       flash.now[:danger] = "No users match this search criteria" if @users.blank?
     end
     respond_to do |format|
       format.js { render partial: 'friends/result' }
 end
end

  def add_friend
    @friend = User.find(params[:friend])
    current_user.friendships.build(friend_id: @friend.id)

    if current_user.save
      flash[:success] = "Friend was successfully added."
    else
      flash[:danger] = "There was something wrong with the friend request."
    end
    redirect_to my_friends_path
  end

  private
  def user_params
    params.require(:user).permit(:username, :password, :avatar)
  end

  def signed_up
    if logged_in?
      flash[:danger] = "You've already signed up for MessageMe"
      redirect_to chatroom_path
    end

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/chatroom/index.html.erb
<h4 class="ui center aligned medium icon header">
  <i class="circular orange coffee icon"></i>
  Say Something
</h4>


<div class="ui two column grid">
  <div class="twelve wide column">
    <div class="ui fluid raised card chatbox">
  <div class="content" id="messages">
<div class="ui feed" id="message-container">
<%= render @messages %>
</div>
</div>
<div class="extra content">
  <%= form_for(@message, html: {class: "ui reply form", role: "form"}, url: message_path, remote: true) do |f| %>

<div class="field">
  <div class="ui fluid icon input">
    <%= f.text_field :body, placeholder: "Say something..." %>
    <%= f.button '<i class="bordered inverted orange edit icon"></i>' .html_safe %>
  </div>
</div>

<% end %>

</div>
</div>
</div>


<div class="four wide column">
  <div class="ui fluid raised card chatbox">
  <div class="content">
<div class="ui inverted vertical menu">
  <a class="active item">
    Friends
  </a>
  <% if current_user.friendships.size > 0 %>
    <% current_user.friends.each do |user| %>
  <a class="item">
     <%= user.username %>
  </a>
  <% end %>
  <% else %>
  <h3 align='center' style="color:white;">Don't have any friends? Add some <%= link_to "here", my_friends_path %>.</h3>
  <% end %>
</div>
</div>
</div>
</div>
</div>

app/views/friends/_lookup.html.erb
<h3>Search for Friends</h3>
<div id="friend-lookup">
  <%= form_tag search_friends_path, remote: true, method: :get, id: 'friend-lookup-form' do %>
<div class="ui search">
  <div class="ui icon input">
    <%= text_field_tag :search_param, params[:search_param], placeholder: "Enter username", autofocus: true,
      class: "prompt" %>
    <i class="search icon"></i>
  </div>
  <%= button_tag(type: :submit, class: "ui orange submit button") do %>
    <i class="fa fa-search"></i> Search
  <% end %>
  <div class="results"></div>
</div>
<% end %>
</div>

<div id="results">
  <%= render 'friends/result' %>
</div>

app/views/friends/_result.html.erb
<% if params[:action] == 'search' %>
  <div class="results-block">
    <%= semantic_flash %>
  </div>
<% end %>
<br>
<% if @users %>
<% if @users.size > 0 %>
  <div id="friend-lookup-results">
<table class="ui selectable inverted table">
  <thead>
    <% @users.each do |user| %>
    <tr>
      <td><strong>Name:</strong> <%= user.username %></td>
      <td><strong>Profile:</strong> <%= link_to "View Profile", user_path(user), class: "ui orange submit button" %>
        <% if current_user.not_friends_with?(user.id) %>
          <%= link_to "Add as my friend",
                  add_friend_path(user: current_user, friend: user), class: "ui orange submit button", method: :post %>
        <% else %>
        <span>
          You are friends
        </span>
        <% end %>
        <% end %>
    </tr>
  </thead>
</table>
</div>
<% end %>
<% end %>

app/views/friends/_result.js.erb
$('#results').html("<%= j(render 'friends/result.html') %>")

app/views/layouts/_footer.html.erb
<body class="Site">
  <header></header>
  <main class="Site-content"></main>
    <div class="container">
      <footer class="footer">
        <small>
          Copyright &copy; <a href="https://www.facebook.com/asadkiprofile" target="_blank">Asad Ullah</a>
        </small>
        <nav>
          <ul>
          </ul>
        </nav>
     </footer>
    </div>
</body>

app/views/layouts/_messages.html.erb
<% flash.each do |message_type, message_content| %>
  <div class="ui <%= message_type %> message transition">
  <i class="close icon"></i>
  <div class="header">
    <%= message_content %>
  </div>
    </div>


<% end %>

app/views/layouts/_navigation.html.erb
<%= link_to "Chatroom", chatroom_path, class: "item" %>
<%= link_to "All Users", users_path, class: "item" %>
<div class="right menu">
  <% if logged_in? %>
  <%= link_to "My Friends", my_friends_path, class: "item" %>
  <% end %>
  <div class="ui dropdown item">
    Account <i class="dropdown icon"></i>
    <div class="menu">
      <% if logged_in? %>
      <%= link_to "Your Profile", user_path(current_user), class: "item" %>
      <%= link_to "Log out", logout_path, method: :delete, class: "item" %>
      <% else %>
      <%= link_to "Log in", login_path, class: "item" %>
      <% end %>
    </div>
  </div>
  <% if !logged_in? %>
  <div class="item">
    <%= link_to "Log in", login_path, class: "ui primary button" %>
  </div>
  <% end %>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MessageMe</title>
    <%= favicon_link_tag %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="ui small inverted menu">
      <div class="ui container">

        <%= render 'layouts/navigation' %>

  </div>
</div>
<div class="ui container">
  <%= render 'layouts/messages' %>
    <%= yield %>

  </div>
  <%= render 'layouts/footer' %>
  </body>

</html>

app/views/messages/_message.html.erb
<div class="event">
  <div class="content">
    <div class="summary">
      <em><%= message.user.username %></em>: <%=  message.body  %>
    </div>
  </div>
</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
<div class="ui error message">
<h2 class="panel-title">
  <%= pluralize(obj.errors.count, "error") %>
  prohibited this user from being created:
</h2>
<ul>
  <% obj.errors.full_messages.each do |msg| %>
  <li><%= msg %></li>
  <% end %>
</div>
</ul>
<% end %>

app/views/users/_form.html.erb
<%= form_for(@user, :html => {class: "ui form", role: "form"}) do |f| %>
  <%= f.label "Profile Picture" %>
      <%= f.file_field :avatar %>
      <p></p>
        <div class="field">
          <%= f.label :username, "Username" %>
          <div class="ui left icon input">
           <%= f.text_field :username, placeholder: "Username" %>
           <i class="user icon"></i>
         </div>

  </div>
  <div class="field">
         <%= f.label :password, "Password" %>
            <div class="ui left icon input">
              <%= f.password_field :password, placeholder: "Password" %>
              <i class="lock icon"></i>
            </div>
  </div>

    <%= f.button "Signup", class: "ui orange submit button" %>

    <h5>Already signed up? <%= link_to "Login", login_path %> </h5>
<% end %>

app/views/users/edit.html.erb
<h1 align="center">Edit your account</h1>

<div class="ui placeholder segment">
  <div class="ui two column very relaxed stackable grid">
    <div class="column">
      <%= form_for(:session, html: {class: "ui form", role: "form"}, url: login_path) do |f| %>
        <div class="field">
          <%= f.label :username, "Username" %>
          <div class="ui left icon input">
            <%= f.text_field :username, placeholder: "Username" %>
            <i class="user icon"></i>
          </div>
        </div>
        <div class="field">
          <%= f.label :password, "Password" %>
          <div class="ui left icon input">
            <%= f.password_field :password, placeholder: "Password" %>
            <i class="lock icon"></i>
          </div>
        </div>

        <%= f.button "Login", class: "ui orange submit button" %>
        <% end %>

app/views/users/index.html.erb
<div align="center">
<h1 align="center">All MessageMe Users</h1>


<div class="pagination apple_pagination">
<%= will_paginate %>
</div>
<br>


<% @users.each do |user| %>
<div class="ui special centered cards">
  <div class="card">
    <div class="blurring dimmable image">
      <div class="ui dimmer">
        <div class="content">
          <div class="center">
            <div class="ui inverted button">
                <% if current_user.not_friends_with?(user.id) %>
                <%= link_to "Add friend",
                    add_friend_path(user: current_user, friend: user), method: :post %>
      
              <% else %>
              <span>
                You are friends
              </span>
              <% end %>
            </div>
          </div>
        </div>
      </div>
        <% if user.avatar.attached? %>
        <image src="<%=(url_for(user.avatar))%>">
        <% else %>
        <%=  image_tag ("blank-profile-picture-973460_960_720.png") %>
        <% end %>
    </div>
    <div class="content">
      <%= link_to user.username, user_path(user) %>
      <div class="meta">
        <span class="date"> Joined
        <%= time_ago_in_words(user.created_at) %> ago</span>
      </div>
    </div>
    <div class="extra content">
      <%= link_to "View Profile", user_path(user), class: "ui orange button"  %>
    </div>
  </div>

</div>
<% end %>
</div>
<br>

<div class="pagination apple_pagination">
<%= will_paginate %>
</div>
<br>

app/views/users/my_friends.html.erb
<h1 align="center">My Friends</h1>

<%= render 'friends/lookup' %>

<% if @friendships.size > 0 %>
  <table class="ui selectable inverted table"">
    <thead>
      <tr>
        <th class="colspan="3"">
          <h2>My Friends</h2>
        </th>
      </tr>
      <tr>
        <th>Name</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @friendships.each do |friend| %>
        <tr>
          <td><b><%= friend.username %></b></td>
          <td>
            <%= link_to "View Profile", user_path(friend) , class: "ui orange submit button"%>
            <%= link_to "Remove Friend", friendship_path(friend), class: "ui orange submit button",
              method: :delete,
              data: { confirm: "Are you sure?" } %>
          </td>
        </tr>
      <% end %>
    </tbody>
  <table>
<% else %>
  <div>
    <p></p>
    <h3>
      You don't have any friends yet, please add some!
    </h3>
  </div>
<% end %>

app/views/users/new.html.erb
<%= render 'shared/errors', obj: @user %>


<h1 align="center">MessageMe - <em>a complete Chat App by Asad</em></h1>

<h4 class="ui center aligned medium icon header">
<i class="circular orange power off icon"></i> Sign up to continue
</h4>


<%= render 'form' %>

app/views/users/show.html.erb
<h1 align="center">Welcome to <%= @user.username %>'s page</h1>

<div align="left center">
  <div class="ui card">
  <div class="image">
    <% if @user.avatar.attached? %>
    <image src="<%=(url_for(@user.avatar))%>">
    <% else %>
    <%=  image_tag ("blank-profile-picture-973460_960_720.png") %>
    <% end %>
  </div>
  <div class="content">
    <p class="header"><%= @user.username %></p>
    <div class="description">
      Kristy is an art director living in New York.
    </div>
  </div>
  <div class="extra content">
    <a>
      <i class="user icon"></i>
      22 Friends
    </a>
  </div>
</div>
</div>